[package]
name = "hm-common"
version = "0.0.0-dev"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Harmont common utilities"
keywords = ["ci", "harmont"]
categories = ["command-line-utilities"]

[lib]
path = "src/lib.rs"

[dependencies]
anyhow      = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
include_dir = "0.7"
tempfile    = "3"
tokio       = { version = "1", features = ["process", "fs"] }
tracing     = "0.1"
which       = "7"

[dev-dependencies]
tempfile    = "3"
tokio       = { version = "1", features = ["macros", "rt-multi-thread"] }
which       = "7"
rstest      = { workspace = true }
proptest    = { workspace = true }

[lints]
workspace = true
